services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - inventory-service
      - order-service
    environment:
      - INVENTORY_SERVICE_URL=http://inventory-service:8081
      - ORDER_SERVICE_URL=http://order-service:8082

  inventory-service:
    build:
      context: ./inventory-service
    ports:
      - "8081:8081"
    environment:
      DB_HOST: db-inventory
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: inventory_service_db
    depends_on:
      - db-inventory

  order-service:
    build:
      context: ./order-service
    ports:
      - "8082:8082"
    environment:
      DB_HOST: db-order
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: order_service_db
      ORDER_SERVICE_PORT: 8082
    depends_on:
      - db-order

  db-order:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_service_db
    ports:
      - "5434:5432"
    volumes:
      - db_order_data:/var/lib/postgresql/data
      - ./order-service/init.sql:/docker-entrypoint-initdb.d/init.sql

  db-inventory:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory_service_db
    ports:
      - "5433:5432"
    volumes:
      - db_inventory_data:/var/lib/postgresql/data
      - ./inventory-service/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_order_data:
  db_inventory_data:
