services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - inventory-service
      - order-service
    environment:
      - INVENTORY_SERVICE_URL=http://inventory-service:8081
      - ORDER_SERVICE_URL=http://order-service:8082

  inventory-service:
    build:
      context: ./inventory-service
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgresql://user:password@db1:5433/inventory
    depends_on:
      - db1

  order-service:
    build:
      context: ./order-service
    ports:
      - "8082:8082"
    environment:
      - DATABASE_URL=postgresql://user:password@db2:5434/orders
    depends_on:
      - db2

  db1:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory
    ports:
      - "5433:5433"
    volumes:
      - db1_data:/var/lib/postgresql/data

  db2:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders
    ports:
      - "5434:5434" 
    volumes:
      - db2_data:/var/lib/postgresql/data

volumes:
  db1_data:
  db2_data: