services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - inventory-service
      - order-service
    environment:
      - INVENTORY_SERVICE_URL=http://inventory-service:8081
      - ORDER_SERVICE_URL=http://order-service:8082

  inventory-service:
    build:
      context: ./inventory-service
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgresql://user:password@db1:5433/inventory
    depends_on:
      - db-inventory

  order-service:
    build:
      context: ./order-service
    ports:
      - "8082:8082"
    environment:
      - DATABASE_URL=postgresql://user:password@db2:5434/orders
    depends_on:
      - db-order

  db-order:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_service_db
    ports:
      - "5433:5432" # Expose this DB on port 5433
    volumes:
      - db_order_data:/var/lib/postgresql/data
      - ./order-service/init.sql:/docker-entrypoint-initdb.d/init.sql

  db-inventory:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory_service_db
    ports:
      - "5434:5432" # Expose this DB on port 5434
    volumes:
      - db_inventory_data:/var/lib/postgresql/data
      - ./inventory-service/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_order_data:
  db_inventory_data: